[build]
  base = "frontend"
  command = "npm run build"
  publish = "build/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200

[functions]
  # React Router 7-nin yaratdığı server funksiyasının yerini Netlify-a göstəririk
  directory = "frontend/.netlify/functions-internal"
  node_bundler = "esbuild"
